
services:
  # app service for your backend
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      DATABASE_NAME: Proyects
      DATABASE_USER: # DATABASE_USER
      DATABASE_PASS: # DATABASE_PASS
      DATABASE_URI: #mongodb://127.0.0.1:27017
      MONGODB_URI: mongodb://127.0.0.1:27017/
      ACCESS_TOKEN_SECRET: MYDEEPSECRET
      ACCESS_TOKEN_EXPIRATION: 900s
      REFRESH_TOKEN_SECRET: MYREFRESHSECRET
      REFRESH_TOKEN_EXPIRATION: 1y
    ports:
      - '4000:4000'
    depends_on:
      - database

  # start the mongodb service as container
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin